#############################################################################
# Makefile for building: test.app/Contents/MacOS/test
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  test/test.pro
# Template: app
# Command: /Users/Leo/Qt/5.8/clang_64/bin/qmake -o Makefile test/test.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -Itest -I. -I/usr/local/Cellar/opencv3/3.2.0/include/opencv -I/usr/local/Cellar/opencv3/3.2.0/include -I../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I../../Qt/5.8/clang_64/lib/QtGui.framework/Headers -I../../Qt/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../Qt/5.8/clang_64/mkspecs/macx-clang -F/Users/Leo/Qt/5.8/clang_64/lib
QMAKE         = /Users/Leo/Qt/5.8/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = test1.0.0
DISTDIR = /Users/Leo/Desktop/Roll_Call_System/.tmp/test1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_LFLAGS) -Wl,-rpath,/Users/Leo/Qt/5.8/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/Leo/Qt/5.8/clang_64/lib -L/usr/local/Cellar/opencv3/3.2.0/lib -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_cvv -lopencv_dpm -lopencv_fuzzy -lopencv_line_descriptor -lopencv_optflow -lopencv_reg -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_rgbd -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_face -lopencv_plot -lopencv_dnn -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_flann -lopencv_xobjdetect -lopencv_objdetect -lopencv_ml -lopencv_xphoto -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_photo -lopencv_imgproc -lopencv_core -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = test/main.cpp \
		test/widget.cpp moc_widget.cpp
OBJECTS       = main.o \
		widget.o \
		moc_widget.o
DIST          = ../Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		../Qt/5.8/clang_64/mkspecs/qdevice.pri \
		../Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		../Qt/5.8/clang_64/mkspecs/common/unix.conf \
		../Qt/5.8/clang_64/mkspecs/common/mac.conf \
		../Qt/5.8/clang_64/mkspecs/common/macx.conf \
		../Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		../Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		../Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.8/clang_64/mkspecs/common/clang.conf \
		../Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		../Qt/5.8/clang_64/mkspecs/qconfig.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		../Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		../Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		../Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		../Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		../Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		../Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		../Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		../Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt/5.8/clang_64/mkspecs/features/link_pkgconfig.prf \
		../Qt/5.8/clang_64/mkspecs/features/qml_debug.prf \
		../Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		../Qt/5.8/clang_64/mkspecs/features/qt.prf \
		../Qt/5.8/clang_64/mkspecs/features/resources.prf \
		../Qt/5.8/clang_64/mkspecs/features/moc.prf \
		../Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.8/clang_64/mkspecs/features/uic.prf \
		../Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		../Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		../Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		../Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		../Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		../Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		../Qt/5.8/clang_64/mkspecs/features/lex.prf \
		test/test/test.pro test/face.h \
		test/widget.h test/main.cpp \
		test/widget.cpp
QMAKE_TARGET  = test
DESTDIR       = 
TARGET        = test.app/Contents/MacOS/test


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d test.app/Contents/MacOS/ || mkdir -p test.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: test/test.pro ../../Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.8/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.8/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.8/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.8/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.8/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.8/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		../../Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.8/clang_64/mkspecs/features/link_pkgconfig.prf \
		../../Qt/5.8/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.8/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.8/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.8/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.8/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.8/clang_64/mkspecs/features/lex.prf \
		test/test.pro \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../Qt/5.8/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile test/test.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../Qt/5.8/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.8/clang_64/mkspecs/qdevice.pri:
../../Qt/5.8/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.8/clang_64/mkspecs/common/unix.conf:
../../Qt/5.8/clang_64/mkspecs/common/mac.conf:
../../Qt/5.8/clang_64/mkspecs/common/macx.conf:
../../Qt/5.8/clang_64/mkspecs/common/sanitize.conf:
../../Qt/5.8/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.8/clang_64/mkspecs/common/clang.conf:
../../Qt/5.8/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.8/clang_64/mkspecs/qconfig.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.8/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.8/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.8/clang_64/mkspecs/features/spec_post.prf:
../../Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.8/clang_64/mkspecs/features/toolchain.prf:
../../Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf:
../../Qt/5.8/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.8/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.8/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.8/clang_64/mkspecs/features/link_pkgconfig.prf:
../../Qt/5.8/clang_64/mkspecs/features/qml_debug.prf:
../../Qt/5.8/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.8/clang_64/mkspecs/features/qt.prf:
../../Qt/5.8/clang_64/mkspecs/features/resources.prf:
../../Qt/5.8/clang_64/mkspecs/features/moc.prf:
../../Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.8/clang_64/mkspecs/features/uic.prf:
../../Qt/5.8/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.8/clang_64/mkspecs/features/qmake_use.prf:
../../Qt/5.8/clang_64/mkspecs/features/file_copies.prf:
../../Qt/5.8/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.8/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.8/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.8/clang_64/mkspecs/features/lex.prf:
test/test.pro:
../../Qt/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../Qt/5.8/clang_64/lib/QtGui.framework/QtGui.prl:
../../Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile test/test.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

test.app/Contents/PkgInfo: 
	@test -d test.app/Contents || mkdir -p test.app/Contents
	@$(DEL_FILE) test.app/Contents/PkgInfo
	@echo "APPL????" > test.app/Contents/PkgInfo
test.app/Contents/Resources/empty.lproj: 
	@test -d test.app/Contents/Resources || mkdir -p test.app/Contents/Resources
	@touch test.app/Contents/Resources/empty.lproj
	
test.app/Contents/Info.plist: 
	@test -d test.app/Contents || mkdir -p test.app/Contents
	@$(DEL_FILE) test.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,notimportant.test,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,test,g" -e "s,@LIBRARY@,test,g" -e "s,@TYPEINFO@,????,g" ../../Qt/5.8/clang_64/mkspecs/macx-clang/Info.plist.app >test.app/Contents/Info.plist

all: Makefile \
		test.app/Contents/PkgInfo \
		test.app/Contents/Resources/empty.lproj \
		test.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents test/face.h test/widget.h $(DISTDIR)/
	$(COPY_FILE) --parents test/main.cpp test/widget.cpp $(DISTDIR)/
	$(COPY_FILE) --parents test/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r test.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp
moc_widget.cpp: ../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QFormLayout \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QImage \
		../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimage.h \
		test/widget.h \
		moc_predefs.h \
		../../Qt/5.8/clang_64/bin/moc
	/Users/Leo/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/Leo/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/Leo/Desktop/Roll_Call_System/test -I/usr/local/Cellar/opencv3/3.2.0/include/opencv -I/usr/local/Cellar/opencv3/3.2.0/include -I/Users/Leo/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/Leo/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/Leo/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/Leo/Qt/5.8/clang_64/lib test/widget.h -o moc_widget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: test/mainwindow.ui \
		../../Qt/5.8/clang_64/bin/uic
	/Users/Leo/Qt/5.8/clang_64/bin/uic test/mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: test/main.cpp test/widget.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QFormLayout \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QImage \
		../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/core.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/cvdef.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/hal/interface.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/version.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/base.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/opencv_modules.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/cvstd.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/ptr.inl.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/neon_utils.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/traits.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/matx.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/saturate.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/fast_math.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/types.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/mat.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/bufferpool.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/mat.inl.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/persistence.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/operations.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/utility.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/core_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/types_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/optim.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/ovx.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/highgui/highgui.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/highgui.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/imgcodecs.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videoio.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/highgui/highgui_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/imgproc/types_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videoio/videoio_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/objdetect.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/opencv.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/calib3d.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/features2d.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/miniflann.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/defines.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/config.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/affine.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/calib3d/calib3d_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/flann_base.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/general.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/matrix.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/params.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/any.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/saving.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/nn_index.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/result_set.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/all_indices.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/kdtree_index.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/dist.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/heap.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/allocator.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/random.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/kmeans_index.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/logger.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/composite_index.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/linear_index.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/lsh_index.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/lsh_table.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/autotuned_index.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/ground_truth.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/index_testing.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/timer.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/sampling.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/imgproc.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/ml.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/photo.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/photo/photo_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/shape.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/shape/emdL1.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/shape/shape_transformer.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/shape/hist_cost.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/shape/shape_distance.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/warpers.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/warpers.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/cuda.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/cuda_types.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/cuda.inl.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/warpers_inl.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/matchers.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/xfeatures2d/cuda.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/motion_estimators.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/util.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/util_inl.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/camera.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/exposure_compensate.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/seam_finders.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/blenders.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/superres.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/superres/optical_flow.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/video.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/video/tracking.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/video/background_segm.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/video/tracking_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/stabilizer.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/global_motion.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/optical_flow.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/motion_core.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/outlier_rejection.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/motion_stabilizing.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/frame_source.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/log.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/inpainting.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/fast_marching.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/fast_marching_inl.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/deblurring.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/wobble_suppression.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/ring_buffer.hpp \
		test/face.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/face.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/face/predict_collector.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/face/facerec.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o test/main.cpp

widget.o: test/widget.cpp test/widget.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QFormLayout \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QImage \
		../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QLayout \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QValidator \
		../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTime \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QLCDNumber \
		../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/core.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/cvdef.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/hal/interface.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/version.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/base.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/opencv_modules.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/cvstd.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/ptr.inl.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/neon_utils.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/traits.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/matx.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/saturate.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/fast_math.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/types.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/mat.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/bufferpool.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/mat.inl.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/persistence.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/operations.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/utility.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/core_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/types_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/optim.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/ovx.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/highgui/highgui.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/highgui.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/imgcodecs.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videoio.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/highgui/highgui_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/imgproc/types_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videoio/videoio_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/objdetect.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/opencv.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/calib3d.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/features2d.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/miniflann.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/defines.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/config.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/affine.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/calib3d/calib3d_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/flann_base.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/general.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/matrix.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/params.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/any.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/saving.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/nn_index.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/result_set.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/all_indices.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/kdtree_index.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/dist.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/heap.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/allocator.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/random.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/kmeans_index.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/logger.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/composite_index.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/linear_index.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/lsh_index.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/lsh_table.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/autotuned_index.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/ground_truth.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/index_testing.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/timer.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/flann/sampling.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/imgproc.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/ml.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/photo.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/photo/photo_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/shape.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/shape/emdL1.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/shape/shape_transformer.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/shape/hist_cost.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/shape/shape_distance.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/warpers.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/warpers.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/cuda.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/cuda_types.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/core/cuda.inl.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/warpers_inl.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/matchers.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/xfeatures2d/cuda.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/motion_estimators.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/util.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/util_inl.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/camera.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/exposure_compensate.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/seam_finders.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/stitching/detail/blenders.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/superres.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/superres/optical_flow.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/video.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/video/tracking.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/video/background_segm.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/video/tracking_c.h \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/stabilizer.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/global_motion.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/optical_flow.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/motion_core.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/outlier_rejection.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/motion_stabilizing.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/frame_source.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/log.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/inpainting.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/fast_marching.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/fast_marching_inl.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/deblurring.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/wobble_suppression.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/videostab/ring_buffer.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/face.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/face/predict_collector.hpp \
		/usr/local/Cellar/opencv3/3.2.0/include/opencv2/face/facerec.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o test/widget.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

